### ISSUE TITLE
What's the minimum react-native version required for this package to work?

### ISSUE THREAD

**Issue by leonardoanalista** [proyecto26/react-native-inappbrowser#17]
it works fine in 0.57 but not in v0.55. I haven't tested on v56 yet.

Here is the error in v.55:

![image](https://user-images.githubusercontent.com/501420/48346013-d15cbc80-e6cd-11e8-9be6-1d8766d6b575.png)

**Comment by jdnichollsc** [comment]
Hi @leonardoanalista 
I have the following configuration from package.json:
```
  "peerDependencies": {
    "react-native": "^0.56.0"
  }
```
If you want I can publish a new version to support `"^0.55.0"`

**Comment by leonardoanalista** [comment]
Thanks for your reply. If it's easy to publish a version that supports v0.55 would be great! We are trying to upgrade to v.56 but the work hasn't started yet.

**Comment by jdnichollsc** [comment]
@leonardoanalista ok, let me do that

**Comment by jdnichollsc** [comment]
Done!

**Comment by leonardoanalista** [comment]
Sorry, I still get the same error in 0.55:
![image](https://user-images.githubusercontent.com/501420/48445121-e3cc1880-e7e9-11e8-9c5a-b006a5743320.png)

**Comment by jdnichollsc** [comment]
Can you share your code?

**Comment by leonardoanalista** [comment]
``` 
 openLink = async url => {
    try {
      await InAppBrowser.isAvailable();
      InAppBrowser.open(url, {
        // iOS Properties
        dismissButtonStyle: 'Done',
        preferredBarTintColor: 'gray',
        preferredControlTintColor: 'white',
        readerMode: true,
        // Android Properties
        showTitle: true,
        toolbarColor: '#6200EE',
        secondaryToolbarColor: 'black',
        enableUrlBarHiding: true,
        enableDefaultShare: true,
        forceCloseOnRedirection: false,
      }).then(result => {
        console.info(JSON.stringify(result));
      });
    } catch (error) {
      console.info(error.message);
    }
  };
...
        <Button
          onPress={() => this.openLink('google.com.au')}
          variant={['wide', 'light']}
        >
          Open url
        </Button>

```
dependency: `    "react-native-inappbrowser-reborn": "1.3.5",`

**Comment by leonardoanalista** [comment]
I messed up with the `url` param. It works perfectly on react-native version 0.55. Thanks you!
