### ISSUE TITLE
Android build breaks due to the release of androidx.browser:browser:1.5.0-alpha01 on June 22th

### ISSUE THREAD

**Issue by xseignard** [proyecto26/react-native-inappbrowser#423]
### Which platform(s) does your issue occur on?
- Android

### Please, provide the following version numbers that your issue occurs with:

- `androidx.browser:browser:1.6.0-beta01` has been released few days ago, see https://android.googlesource.com/platform/frameworks/support/+/635f86783709c977282f9867d5bcd7662c884df0
- only compatible with `compileSdkVersion` 34
- but most of RN/expo apps rely on `compileSdkVersion` 33
- since June 22th, `androidx.browser:browser:1.+` resolves to `androidx.browser:browser:1.6.0-beta01` due to this code: https://github.com/proyecto26/react-native-inappbrowser/blob/develop/android/build.gradle#L55-L64

### Please, tell us how to recreate the issue in as much detail as possible. 
Build on android

### How to fix?
Add a `androidXBrowser = "1.5.0"` in your project `android/build.gradle`:
```
buildscript {
    ext {
        // ...
        androidXBrowser = "1.5.0"
```

### It already happened before

See this issue: https://github.com/proyecto26/react-native-inappbrowser/issues/386

See this issue: https://github.com/proyecto26/react-native-inappbrowser/issues/298

A more robust solution (e.g. fixed version instead of `1.+`) would be great

It happens all the time...

**Comment by SophieJung7** [comment]
Can you guys fix this asap? Don't want to change android/build.gradle file...:(

**Comment by hbel** [comment]
FYI, for those of you using Expo, I think I have found (a quite hacky) workaround to be able to at least build your android binaries locally again (without ejecting your whole project).

You can (of course) edit the gradle file as given in PR #424 to use version 1.5.0, locally, but since metro is running yarn install by itself when building with eas build --local, it will not be enough to make if you only do so in your local node_modules. You also have to change the file in yarn's cache directory, too. After that (and maybe clearing your gradle caches, too), you should be able to build again (until you clear yarn's cache, of course). At least, that worked for me.

**Comment by xseignard** [comment]
please don't use @hbel solution 😬 

rely on a custom dev client (see: https://docs.expo.dev/develop/development-builds/introduction/)

and use a custom plugin to change `androidXBrowser` in the `ext`, you can have a look at this one https://github.com/transistorsoft/expo-gradle-ext-vars

**Comment by ROG3R-DEV** [comment]
Adding androidXBrowser="1.5.0" didn't solve the problem for me.

  "react-native-inappbrowser-reborn": "3.7.0",

`buildscript {
    ext {
        androidXBrowser = "1.5.0"
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }`

Any idea?

**Comment by hbel** [comment]
I'm terribly sorry for causing that confusion. I actually tried to set the ext vars first, but seemed to have not cleared all the caches, so it did not work. I can confirm that this solution works - tried it in several projects.

**Comment by HiveForensicsAI** [comment]
I got it to work very simply it took me a few hours of trying different solutions but ultimately my solution was solved by  

   "plugins": [
      ["expo-gradle-ext-vars", { "androidXBrowser": "1.4.0" }]
    ]
  }
}

**Comment by krini** [comment]
My app still crashes though I added androidXBrowser = "1.5.0" in android/build.gradle file.
Do I need to do something else?
I'm using 
"react-native-inappbrowser-reborn": "^3.7.0"
"react-native": "0.71.13",

**Comment by esbenvb** [comment]
> My app still crashes though I added androidXBrowser = "1.5.0" in android/build.gradle file. Do I need to do something else? I'm using "react-native-inappbrowser-reborn": "^3.7.0" "react-native": "0.71.13",

In `android/app/build.gradle` add this:

```
configurations.all {
   resolutionStrategy {
    force 'androidx.browser:browser:1.5.0'
   }
}
```

**Comment by martinsotirov** [comment]
> I got it to work very simply it took me a few hours of trying different solutions but ultimately my solution was solved by adding the plugins to the app.json for my expo project also making sure to format it correctly and install vars this solution was recommended already previously so this is nothing new
> 
> "plugins": [ ["expo-gradle-ext-vars", { "androidXBrowser": "1.4.0" }] ] } }

This turned out to be the correct answer for our case.

**Comment by jamesleeht** [comment]
The current build seems to set the version as: androidx.browser:browser:1.8.0-alpha01.

expo-gradle-ext-vars solution does not seem to work as intended anymore.
